name: package-manager-ci
on:
  push:
    branches:
      - main
      - package-manager-load
permissions:
  contents: read
env:
  PNPM_CI: true
jobs:
  pnpm:
    name: pnpm package manager on ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ^9.0.0
      - name: Install dependancies
        run: pnpm install
      - name: Tests
        run: pnpm run test-ci-pnpm
